### PR TITLE
Added multi-provider multi-instance functionality

### PR DESCRIPTION
**Pull request by PakDLiu**
Added multi-provider multi-instance functionality
Notable changes:
- Added new API version 2020-02-07-preview
   - Split the `module_sdk `directory into 2, `module_sdk/v2017_11_03_preview` for the old version and `modules_sdk/v2020_02_07_preview` for the new
- Provider instance operations will use the new API version
- HANA instance operation will still use the old API version (no change)
- SAP Monitor operation will attempt to use the new API version, if it fails, it will use to old API version

### CODE REVIEW

**Comment by persiaAziz-zz** [comment]
According to your description: PUT SapMonitor will use 2020-02-07 intially and if fails will try to use the old API version. Doesn't the old API version expect Hana Properties to be passed?

**Comment by PakDLiu** [comment]
yes, all those hana fields are not optional.
it will try to use version 2020-02-07, ignoring the hana fields
if that fails, it will use version 2017-11-03 passing in the hana fields

**Review by dwj300 — APPROVED** [review]
lgtm

**Review by persiaAziz-zz — APPROVED** [review]
lgtm

**Pull request merged**
