### PR TITLE
attempting old api version message will be sent to logger debug rather than printing

### PR DESCRIPTION
**Pull request by PakDLiu**
Debug messages should not be printed, logging to debug instead

### CODE REVIEW

**Comment by PakDLiu** [comment]
```
msrest.http_logger : {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus2' and API version '2020-02-07-preview' for type 'sapMonitors'. The supported api-versions are '2017-11-03-preview, 2020-02-07-preview'. The supported locations are 'westus, westus2, eastus, eastus2, westeurope, northeurope, japaneast, japanwest, australiaeast, australiasoutheast, southeastasia, southcentralus, uksouth'."}}
msrest.exceptions : Operation returned an invalid status code 'Bad Request'
Operation returned an invalid status code 'Bad Request' Attempting old API version
Getting management service client client_type=HanaManagementClient
msrest.universal_http.requests : Configuring retry: max_retries=4, backoff_factor=0.8, max_backoff=90
```

**Comment by lagalbra** [comment]
FYI for other reviewers, I checked there are no other files in this repo which use `print` besides custom.py

**Comment by lagalbra** [comment]
nit: also show example of what the output looked like before this change

**Review by lagalbra — APPROVED** [review]

**Comment by PakDLiu** [comment]
its hard to show because the message is the same, just different colors...

**Review by dwj300 — APPROVED** [review]
lgtm

**Pull request merged**
